### ISSUE TITLE
throws some error

### ISSUE THREAD

**Issue by actuallyabhi** [rahul-vashishtha/nodegui-deb-builder#1]
Cleaning DEBIAN:
<Buffer >
Cleaning bin:
<Buffer >
Cleaning lib:
<Buffer >
Cleaning applications:
<Buffer >
Copying control:
<Buffer >
Copying Build Folder:
<Buffer >
<Buffer >
mv: cannot move './deb-struct/usr/lib/react-nodegui-starter' to a subdirectory of itself, './deb-struct/usr/lib/react-nodegui-starter/react-nodegui-starter'
child_process.js:650
    throw err;
    ^

Error: Command failed: mv "./deb-struct/usr/lib/react-nodegui-starter" ./deb-struct/usr/lib/react-nodegui-starter
mv: cannot move './deb-struct/usr/lib/react-nodegui-starter' to a subdirectory of itself, './deb-struct/usr/lib/react-nodegui-starter/react-nodegui-starter'

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at copyBuildFolderToLib (/home/abhishek/Desktop/projects/react-nodegui-starter/build-deb.js:29:25)
    at Object.<anonymous> (/home/abhishek/Desktop/projects/react-nodegui-starter/build-deb.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6d 76 3a 20 63 61 6e 6e 6f 74 20 6d 6f 76 65 20 27 2e 2f 64 65 62 2d 73 74 72 75 63 74 2f 75 73 72 2f 6c 69 62 2f 72 65 61 63 74 2d 6e 6f 64 65 67 75 ... 107 more bytes>
  ],
  pid: 21344,
  stdout: <Buffer >,
  stderr: <Buffer 6d 76 3a 20 63 61 6e 6e 6f 74 20 6d 6f 76 65 20 27 2e 2f 64 65 62 2d 73 74 72 75 63 74 2f 75 73 72 2f 6c 69 62 2f 72 65 61 63 74 2d 6e 6f 64 65 67 75 ... 107 more bytes>
}
abhishek@abhishek-FMVDE2A0L1:~/Desktop/projects/react-nodegui-starter$ node build-deb.js
Cleaning DEBIAN:
<Buffer >
Cleaning bin:
<Buffer >
Cleaning lib:
<Buffer >
Cleaning applications:
<Buffer >
Copying control:
<Buffer >
Copying Build Folder:
<Buffer >
<Buffer >
mv: cannot move './deb-struct/usr/lib/react-nodegui-starter' to a subdirectory of itself, './deb-struct/usr/lib/react-nodegui-starter/react-nodegui-starter'
child_process.js:650
    throw err;
    ^

Error: Command failed: mv "./deb-struct/usr/lib/react-nodegui-starter" ./deb-struct/usr/lib/react-nodegui-starter
mv: cannot move './deb-struct/usr/lib/react-nodegui-starter' to a subdirectory of itself, './deb-struct/usr/lib/react-nodegui-starter/react-nodegui-starter'

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at copyBuildFolderToLib (/home/abhishek/Desktop/projects/react-nodegui/build-deb.js:29:25)
    at Object.<anonymous> (/home/abhishek/Desktop/projects/react-nodegui/build-deb.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6d 76 3a 20 63 61 6e 6e 6f 74 20 6d 6f 76 65 20 27 2e 2f 64 65 62 2d 73 74 72 75 63 74 2f 75 73 72 2f 6c 69 62 2f 72 65 61 63 74 2d 6e 6f 64 65 67 75 ... 107 more bytes>
  ],
  pid: 21421,
  stdout: <Buffer >,
  stderr: <Buffer 6d 76 3a 20 63 61 6e 6e 6f 74 20 6d 6f 76 65 20 27 2e 2f 64 65 62 2d 73 74 72 75 63 74 2f 75 73 72 2f 6c 69 62 2f 72 65 61 63 74 2d 6e 6f 64 65 67 75 ... 107 more bytes>
}

**Comment by rahul-vashishtha** [comment]
Hi @mabhishek7081 
Seems likes there is some recursion in your directory structure. Can you share your folder structure screenshot?

**Comment by saitho** [comment]
This happens when the name already is lowercase and has no spaces, as `appName.replace(' ', '').toLowerCase()` is the same as before. This results in moving folder into itself.
